//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvh_Aspnet_Lesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lvh_TACGIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lvh_TACGIA()
        {
            this.Lvh_SACH = new HashSet<Lvh_SACH>();
        }
    
        public string Lvh_MaTG { get; set; }
        public string Lvh_TenTG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lvh_SACH> Lvh_SACH { get; set; }
    }
}
