//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lvh_Aspnet_Lesson12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lvh_SACH
    {
        public string Lvh_MaSach { get; set; }
        public string Lvh_TenSach { get; set; }
        public Nullable<int> Lvh_SoTrang { get; set; }
        public Nullable<int> Lvh_NamXB { get; set; }
        public string Lvh_MaTG { get; set; }
        public Nullable<bool> Lvh_TrangThai { get; set; }
    
        public virtual Lvh_TACGIA Lvh_TACGIA { get; set; }
    }
}
